## merging data

```{r echo=FALSE}
library("knitr")
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(output = function(x, options) {
   lines <- options$output.lines
   if (is.null(lines)) {
     return(hook_output(x, options))  # pass to default hook
   }
   x <- unlist(strsplit(x, "\n"))
   more <- "..."
   if (length(lines)==1) {        # first n lines
     if (length(x) > lines) {
       # truncate the output, but add ....
       x <- c(head(x, lines), more)
     }
   } else {
     x <- c(if (abs(lines[1])>1) more else NULL,
            x[lines],
            if (length(x)>lines[abs(length(lines))]) more else NULL
           )
   }
   # paste these lines together
   x <- paste(c(x, ""), collapse = "\n")
   hook_output(x, options)
 })

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE
)
```

##

```{r}
library('taxize')
```

## Get ids from many sources at once

```{r output.lines=1:15}
out <- get_ids(names = "Poa annua", db = c('ncbi', 'itis', 'col', 'tropicos'))
out
```

```{r}
out$col
```

## From single source, e.g,: ITIS

```{r}
get_tsn("Poa annua")
```

## Coerce a name or id to a taxon identifier class

```{r}
get_gbifid("Poa annua")
```

```{r}
as.gbifid("2704179")
```

## Many names - the ids class

In this case get many identifiers for many names

```{r output.lines=1:15}
mynames <- c("Helianthus annuus", "Pinus contorta", "Collomia grandiflora")
out <- get_ids(names = mynames, db = c('ncbi','itis','col','tropicos'))
```

```{r}
out$tropicos
```

```{r}
class(out)
```

```{r}
class(out$col)
```
