---
title: "taxonomic data"
output:
  revealjs::revealjs_presentation:
    theme: solarized
    transition: none
    highlight: pygments
    reveal_options:
      slideNumber: true
---

## taxonomic names

* Taxonomic names used by nearly everyone
<br><br>
* After names are cleaned, integrate with other parts of research workflow
    * taxonomy -> biodiversity data
    * taxonomy -> phylogenetics
    * taxonomy -> molecular work

## taxize

Source: [https://github.com/ropensci/taxize](https://github.com/ropensci/taxize)
<br>
CRAN: [https://cran.rstudio.com/web/packages/taxize/](https://cran.rstudio.com/web/packages/taxize/)

## taxize - two organizing principles

- Data sources
    - Lots of data sources, currently 20
- Verbs (ish)
    - `classification()`
    - `children()`
    - `downstream()`
    - `upstream()`
    - `comm2sci()` / `sci2comm()`
    - `resolve()`
    - `synonyms()`
    - `lowest_common`

## Why taxize?

> A single easy to use user interface to many data sources can simplify science, and make it more reproducible

## Other taxonomic tools

* `taxa` - taxonomic classes - in development [https://github.com/ropenscilabs/taxa](https://github.com/ropenscilabs/taxa)
* `binomen` - manipulations on taxonomic classes - [https://github.com/ropenscilabs/binomen](https://github.com/ropenscilabs/binomen)
* `taxizedb` - taxonomic databases - [https://github.com/ropenscilabs/taxizedb](https://github.com/ropenscilabs/taxizedb)

## taxizedb

Entire taxonomic databases - or - I want all the data

```r
devtools::install_github("ropenscilabs/taxizedb")
library("taxizedb")
```

```r
db_download_col()
db_load_col("~/.taxize_local/col.sql")
src <- src_col()
tbl <- tbl(src, "hierarchy")
tbl %>% select(tsn, childrencount)
sql_collect(src, "select * from taxonomic_units where tsn = '54'")
```

## Lessons & Exercises

__Lessons__

* Names
* Identifiers
* Classifications

__Exercises__

* Working with taxonomic identifiers
* Scientific & common name conversion
* Downstream
